### ISSUE TITLE
Android - Change to push delivery method 

### ISSUE THREAD

**Issue by rjambula** [Marketing-Suite/android-sdk#4] opened 2017-06-13 19:09 UTC
Change to push delivery method for Android to allow for both push registration call back methods to also perform the open, but not display anything, as McClatchy has their own logic/UX for a push notification.
           o   In backlog to be reviewed with development (38121)

**Comment by ClientDeveloperRelations** [comment] 2017-06-19 19:19
Weekly meeting: callback cannot be called when app is in closed state, so this is a dependency on the push calling the callback when closed in order to confirm.

**Comment by ClientDeveloperRelations** [comment] 2017-06-23 20:00
Duplicate of [Issue 1](https://github.com/Marketing-Suite/android-sdk/issues/1)

**Closed as completed by ClientDeveloperRelations** 2017-06-23 20:00 UTC
Labels: duplicate
